### ISSUE TITLE
`renderBadge()` does not send value or react

### ISSUE THREAD

**Issue by nteetor** [nteetor/yonder#88]
@jcheng5 and @wch, as you have time I would appreciate any help you can offer regarding something of a mysterious bug. 

I have created a custom reactive output, see [badgeOutput](https://github.com/nteetor/dull/blob/master/R/badge.R#L53). The `renderBadge` function uses the new tools, `installExprFunction` and `createRenderFunction`, no errors. 

However, `renderBadge` does not react nor will it pass along a static value. In examples I have run the inputs and outputs are found and bound on the client-side. The other `render*` functions in the package continue to work and most have been converted to the new style. 

Do you have any initial thoughts as to why a custom render function might silently fail like this? Thank you in advance!

**Comment by nteetor** [comment]
I have tried using a different render function, `renderText`, to send dummy data to the badge output. Still nothing happened (using `options(shiny.trace = TRUE)`), which suggests the problem lies with the `output` object and not necessarily the render function.

**Comment by nteetor** [comment]
Shiny appears to be treating the element created by `badgeOutput()` as a hidden element. I was able to get the render function reacting with `outputOptions(.., suspendWhenHidden = FALSE)`. 

Here is the application I am running, 
```R
shinyApp(
  ui = container(
    badgeOutput("mybadge")
  ),
  server = function(input, output) {
    output$mybadge <- renderBadge({
      "hello, world"
    })
    outputOptions(output, "mybadge", suspendWhenHidden = FALSE)
  }
)
```

The element does not appear to be hidden, 
![image](https://user-images.githubusercontent.com/3228369/42093255-b110137e-7b79-11e8-8d75-ae88a3f3fc9d.png)

I will track down the relevant shiny code to get an idea of what is happening under the hood.

**Comment by wch** [comment]
I think the problem is Bootstrap's styling for `badge:empty`:

![image](https://user-images.githubusercontent.com/86978/42099863-358c58ec-7b84-11e8-9466-31e5183aa325.png)

Because it starts with `display:none`, Shiny will suspend the output. I think if you override it with something this it should work:

```css
.badge:empty {
  display: inline-block;
}
```

A tip: I suggest using the `shiny.minified` option to allow the user to choose to load the un-minified version of dull.js with `options(shiny.minified=FALSE)`. That will make it easier debug and step through the Javascript code. Also, if you build with source maps, that can help to debug even when it's minified.

Here's how Shiny uses `shiny.minified`:
https://github.com/rstudio/shiny/blob/750aaf451a2c9b1a84f8341c5f94ac7e29f242bf/R/shinyui.R#L49

**Comment by nteetor** [comment]
Good catch, thank you Winston. This seemingly complex issue devolved into quite a minor one.

Thank you, too, for the tip about `shiny.minified`. Would you recommend using a new option or piggybacking on `shiny.minified`?

**Comment by wch** [comment]
I'd suggest just using `shiny.minified` -- I think it makes sense to basically have the Javascript code for your app to be completely in debug mode or not.

**Comment by wch** [comment]
Not sure if this matters for your use case, but `display: contents` is apparently not supported by IE or Edge.

https://caniuse.com/#feat=css-display-contents

**Comment by nteetor** [comment]
Yes, unfortunately that matters. Bootstrap 4 supports IE 10+ and Edge 12+, so I am following suit.
